#!/usr/bin/env python3
"""Emit tunable_configs.inc by enumerating the full cartesian product of
the tunable knobs, filtered to launchable configurations.

Knobs (powers-of-two):
    BDX in {8, 16, 32}      (threads.x per block)
    BDY in {8, 16, 32}      (threads.y per block)
    TX  in {1, 2, 4, 8}     (output cols per thread; register tile)
    TY  in {1, 2, 4, 8}     (output rows per thread; register tile)
    TK  in {8, 16, 32}      (K tile loaded into shared memory)

Filters:
    32 <= BDX*BDY <= 1024              (launch limit on threads/block)
    (BDY*TY + BDX*TX) * TK * 4 <= 48 KB (default static smem per block)
"""

import sys

BDX_RANGE = [8, 16, 32]
BDY_RANGE = [8, 16, 32]
TX_RANGE  = [1, 2, 4, 8]
TY_RANGE  = [1, 2, 4, 8]
TK_RANGE  = [8, 16, 32]

MIN_TPB    = 32
MAX_TPB    = 1024
MAX_SMEM_B = 48 * 1024


def enumerate_configs():
    rows = []
    for bdx in BDX_RANGE:
        for bdy in BDY_RANGE:
            tpb = bdx * bdy
            if not (MIN_TPB <= tpb <= MAX_TPB):
                continue
            for tx in TX_RANGE:
                for ty in TY_RANGE:
                    for tk in TK_RANGE:
                        block_m = bdy * ty
                        block_n = bdx * tx
                        smem = (block_m + block_n) * tk * 4
                        if smem > MAX_SMEM_B:
                            continue
                        rows.append((bdx, bdy, tx, ty, tk))
    rows.sort()
    return rows


def main(out_path):
    rows = enumerate_configs()
    with open(out_path, "w") as f:
        f.write("// Auto-generated by gen_configs.py -- do not edit by hand.\n")
        f.write(f"// {len(rows)} configurations.\n")
        for bdx, bdy, tx, ty, tk in rows:
            name = f"B{bdx:02d}x{bdy:02d}_T{tx}x{ty}_K{tk:02d}"
            f.write(f'CFG("{name}", {bdx}, {bdy}, {tx}, {ty}, {tk}),\n')
    print(f"Generated {len(rows)} configs -> {out_path}", file=sys.stderr)


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "tunable_configs.inc"
    main(out)
